name: Publish Release

on:
  push:
    tags: 
      - 'v**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Compression
      run: |
        cd target
        tar zcvf socks5-proxy.tar.gz release/
        mv socks5-proxy.tar.gz ../
        cd ..
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
        file: "*.tar.gz"
        # If you need to overwrite existing files, add overwrite: true to the with.
        overwrite: true
        # The resultant deployment is a draft Release that only repository collaborators can see. This gives you an opportunity to examine and edit the draft release.
        draft: false
        # The resultant deployment is a Prerelease. This gives you an opportunity to examine and edit the prerelease.
        prerelease: false
        # With tags: true, your Releases deployment will trigger if and only if the build is a tagged build.
        tags: ${{ github.ref }}
    
